name: Build (Linux)
on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v6

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libqalculate23

      - name: Release Build With Cmake
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -S $PWD -B cmake-build-release
          cmake --build cmake-build-release

      - name: Upload Release Build
        uses: actions/upload-artifact@v6
        with:
          name: "juno"
          path: "juno"